[package]
name = "dec_gl"
version = "0.3.5"
edition = "2021"

[dependencies]
gl = "0.14.0"
glm = "0.2.3"
glfw = {version = "0.59.0"}
image = "0.25.5"
toml = "0.8.19"
thiserror = "2.0.11"
mockall = "0.13.1"
mockall_double = "0.3.1"
impl_ops = "0.1.1"
